# Generated by Django 5.2 on 2025-04-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='img_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
